### ISSUE TITLE
There is no dropdown with databases list

### ISSUE THREAD

**Issue by silentsokolov** [ClickHouse/clickhouse-tableau-connector-jdbc#65]
This is the same issue as #62 
In the Tableau version 2023.3, with any combination of drivers and settings, the dropdown list is missing

---
Tableau Desktop v2023.3.x (and WebView on Server v2023.3.x)
ClickHouse v23.8.2.7
clickhouse-tableau-connector-jdbc v0.2.6
Clickhouse JDBC driver: 0.6.0 / 0.5.0 / 0.4.6 /  0.3.2-patch8 / 0.3.2-patch11
Settings: `databaseTerm=schema`, `databaseTerm=catalog`, `database=default` (and spec)

**Comment by yurifal** [comment]
Do simply adding the `databaseTerm=schema` 
to the Custom Connection Parameters 
on the Advanced tab work for you?

It does work for me (and other users as well):
https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/issues/62#issuecomment-1848958680

**Comment by yurifal** [comment]
setting the `databaseTerm=catalog` 
or specifying the `database=<some_name>` 
doesn't work.

**Comment by silentsokolov** [comment]
> any combination of drivers and settings
yes, a try 
databaseTerm=schema, databaseTerm=catalog w + w/o database=default, database=<some>

**Comment by yurifal** [comment]
could you please share the **Advanced** tab screenshot of your connection dialog?

**Comment by yurifal** [comment]
for a positive test, please try connecting to this instance:

`github.demo.trial.altinity.cloud (8443 demo:demo)`

**Comment by silentsokolov** [comment]
On screen 

WebView on Server v2023.3.x
ClickHouse v23.8.2.7
clickhouse-tableau-connector-jdbc v0.2.6
Clickhouse JDBC driver: 0.4.6

w/o `database=<some>` - nothing change

<img width="200" alt="image" src="https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/assets/398939/6d92a14f-40af-4592-820b-ff37d8898109">
<img width="200" alt="image" src="https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/assets/398939/acbf356f-41bb-4c64-aeca-954b0c7af3d5">
<img width="200" alt="image" src="https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/assets/398939/a13854e2-d394-446e-93a2-3d31e09b669f">

**Comment by silentsokolov** [comment]
On screen

WebView on Server v2023.3.x
ClickHouse ???? (`github.demo.trial.altinity.cloud`)
clickhouse-tableau-connector-jdbc v0.2.6
Clickhouse JDBC driver: 0.4.6

And yes, it's works

<img width="288" alt="image" src="https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/assets/398939/999178f3-a423-413c-9afb-9d4c2481a798">

**Comment by yurifal** [comment]
Their version: 

`SELECT version();

version() |
----------+
23.10.5.20|
`

**Comment by yurifal** [comment]
please DO NOT add `database=default` to the Connection Parameters

**Comment by silentsokolov** [comment]
> please DO NOT add database=default to the Connection Parameters

w/o `database=<some>` - nothing change )))

**Comment by yurifal** [comment]
There's something with the settings of your CH instance, i guess.
Could you please ask your CH DBA if any changes made to the configs 
regarding the metadata queries (catalog/schema/table)?

**Comment by yurifal** [comment]
Are you able to connect from yet another SQL client using JDBC (DBeaver etc)?
Could you try connecting from DBeaver using the `databaseTerm=schema` set in the Driver Properties?

**Comment by silentsokolov** [comment]
Finally, problem is an option `enable_http_compression`, we must force disable it.

Thx

<img width="137" alt="image" src="https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/assets/398939/33d6d1b8-604b-4064-a0e4-2746049f4766">
