### ISSUE TITLE
SSLRootCert for Tableau Server

### ISSUE THREAD

**Issue by noblesm19** [ClickHouse/clickhouse-tableau-connector-jdbc#71]
Via Tableau Desktop it works fine while configuring the SSLRootCert for the connection, however, once published to Tableau Server, how do we allow for the same cluster to use the cert in Tableau Server? Heres the resulting error:

PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, server ClickHouseNode

**Comment by yurifal** [comment]
It's safe to put the CA cert to /etc/ssl/certs 
and make sure the same path is written in the Connection.

**Comment by noblesm19** [comment]
Mmmm, if there are mac and windows users, then we'd have to put it in a common place for people to use. Do you know off hand if we put it on an NFS that mac users can have the smb path translate to \\ for tableau server to see?

**Comment by yurifal** [comment]
/etc/ssl/certs is for linux & macos
C:\etc\ssl\certs is for windows

And the parameter to put in the Advanced Tab:
<img width="510" alt="Screenshot 2024-03-28 at 21 03 45" src="https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/assets/2496788/ed74db83-9906-4429-be79-18e60896b26f">

**Comment by Pavanjreddy** [comment]
Thanks for the update, I have an other question, by default sslmode is taking as STRICT, where should we set it to make it NONE?

**Comment by yurifal** [comment]
Simply don't use SSL, change the port to be 8123 (http)

**Comment by Pavanjreddy** [comment]
> Simply don't use SSL, change the port to be 8123 (http)

I want to keep ssl=true and sslmode=NONE, how do we do it? we can set it up is JDBC driver properties from jdbc based database connectivity tools.

**Comment by artshevchenko** [comment]
You can change Custom Connection Parameters on Advanced tab, for example: `socket_timeout=300000,ssl=true,sslmode=NONE`

**Comment by Pavanjreddy** [comment]
> You can change Custom Connection Parameters on Advanced tab, for example: `socket_timeout=300000,ssl=true,sslmode=NONE`

@artshevchenko @yurifal , even after setting the above, it is failing with the same error, it is still taking sslmode=STRICT, can you check?

unable to find valid certification path to requested target, server ClickHouseNode [uri=https://xxxxx.xxxxx.com:8443/default, options={custom_http_params=join_use_nulls=1,session_id=tableau-jdbc-connector-1712682126579-38786521,typeMappings=UInt64=java.lang.String,UInt128=java.lang.String,Int128=java.lang.String,UInt256=java.lang.String,Int256=java.lang.String,socket_timeout=300000,sslmode=STRICT}]@-358081908
Unable to connect to the ClickHouse JDBC by ClickHouse, Inc. server "arcadia.teslamotors.com". Check that the server is running and that you have access privileges to the requested database.
Connector Class: clickhouse_jdbc, Version: 0.2.6
[For support, contact ClickHouse, Inc..](https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/issues)

**Comment by yurifal** [comment]
> > You can change Custom Connection Parameters on Advanced tab, for example: `socket_timeout=300000,ssl=true,sslmode=NONE`
> 
> @artshevchenko @yurifal , even after setting the above, it is failing with the same error, it is still taking sslmode=STRICT, can you check?

Please do what @artshevchenko has suggested, but simply **remove** the SSL flag on the main tab.

**Comment by Pavanjreddy** [comment]
Database connectivity tools that uses JDBC driver, we are setting ssl=true and sslmode=NONE and we are able to connect without any issue over port 8443, but when we do the same thing on tableau desktop, it is failing with "unable to find valid certification path to requested target", we want to get this resolved, @yurifal, you suggested to place the ssl root cert under C:\etc\ssl\certs in windows, but that path doesn't exists. Please check from your side and let us know a possible workaround or a fix for this issue.

**Comment by yurifal** [comment]
Create the dir `C:\etc\ssl\certs` and make sure users to have the read-only access to the files (similar to *nix mod 644).
btw are we talking about the Root CA certificate (of the Certificate Authority which you've singed your CH cert with)?

**Comment by Pavanjreddy** [comment]
> Create the dir `C:\etc\ssl\certs` and make sure users to have the read-only access to the files (similar to *nix mod 644). btw are we talking about the Root CA certificate (of the Certificate Authority which you've singed your CH cert with)?

yes, its the root CA cert.

**Comment by noblesm19** [comment]
Apologies for the delay and thanks for the support @yurifal. Unfortunately, it's still the same issue with the root cert on each host. We're installed on the D drive; and I put this path/file on the C and D drive to just to be sure

**Comment by yurifal** [comment]
Hi @noblesm19 and @Pavanjreddy 

Here are all my suggestions in one place:

1) Clear the SSL flag on the General Tab:
<img width="510" alt="Screenshot 2024-04-11 at 19 16 21" src="https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/assets/2496788/4da754a6-8618-4f7c-863b-c87f1ad0efc0">

2) add the SSL parameters to the connection string on the Advanced Tab:
<img width="511" alt="Screenshot 2024-04-11 at 19 17 24" src="https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/assets/2496788/02943c08-c8ed-4f14-9027-b8c75eec630c">

That's it (imho).

**Comment by noblesm19** [comment]
That worked! You're the best!
