### ISSUE TITLE
Not able to set sslmode=NONE

### ISSUE THREAD

**Issue by marshalladd** [ClickHouse/clickhouse-tableau-connector-jdbc#73]
In advanced settings I need to set sslmode=NONE, but it stays always STRICT when SSL enabled in general tab.

**Comment by artshevchenko** [comment]
Hi! You can use the solution from this issue: [Issue #71](https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/issues/71)

**Comment by marshalladd** [comment]
Solution: disable SSL in General tab, but in advanced tab add: ssl=true,sslmode=NONE
